<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoMovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoMovimientoRepository extends EntityRepository
{
}
