<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VehiculoObjetoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoObjetoRepository extends EntityRepository
{
}
